@startuml

skinparam defaultTextAlignment center

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.3.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons2/docker.puml
!includeurl ICONURL/devicons2/oracle_original.puml
!includeurl ICONURL/devicons2/ubuntu_wordmark.puml
!includeurl ICONURL/devicons2/windows8_original.puml
!include <cloudogu/tools/docker.puml>
!include <cloudogu/tools/terraform.puml>
!include <cloudogu/tools/terraform.puml>
!include <tupadr3/devicons2/vagrant_wordmark.puml>

node "Architecture" as a {
node "Container / Images" as c {
  TOOL_DOCKER(build_app_1, Infrastructure Build, node) {
    node "Infrastructure\nCI" as build_ci_1
    node "Infrastructure\nRegistry" as build_depl_1
    build_ci_1 -[hidden]right- build_depl_1
  }
  build_ci_1 ---> ci

  TOOL_DOCKER(adf_app_1, ADF App1, node) {
    node "ADF\nCI" as adf_ci_1
    node "ADF\nDeployment" as adf_depl_1
    adf_ci_1 -[hidden]right- adf_depl_1
  }
  adf_depl_1 ---> adf
  adf_ci_1 ---> ci

  TOOL_DOCKER(fr_app_1, FR App1, node) {
    node "ADF\nCI" as fr_ci_1
    node "ADF\nDeployment" as fr_depl_1
    fr_ci_1 -[hidden]right- fr_depl_1
  }
  fr_depl_1 ---> fr
  fr_ci_1 ---> ci

  TOOL_DOCKER(ci, CI Image, node) {
    node "Jenkins\nController" as ci_jc
    node "Jenkins\nAgents" as aja
    node "Sonarcube" as ajs
    ci_jc --> aja
    aja --> ajs
  }

  TOOL_DOCKER(adf, ADF Image, node) {
    node "WebLogic" as adf_wl
    node "Datenbank" as adf_db
    adf_wl --> adf_db
  }
  ci -[hidden]right- adf

  TOOL_DOCKER(fr, F&R Image, node) {
    node "WebLogic" as fr_wl
    node "Datenbank" as fr_db
    fr_wl --> fr_db
  }
  adf -[hidden]right- fr
}
node "Infrastructure" as i {
  TOOL_DOCKER(dc, Docker\nCompose, node)
  TOOL_TERRAFORM(ioci,Terraform) {
    DEV2_ORACLE_ORIGINAL(oci, Oracle Compute Instance\n(Cloud), cloud) {
      DEV2_UBUNTU_WORDMARK(ociubuntu, Server) {
        TOOL_DOCKER(ocidockerce, Docker CE) {
        }
      }
    }
  }

  DEV2_WINDOWS8_ORIGINAL(idw) {
    TOOL_DOCKER(wdd, Docker Desktop\n(Local)) {
    }
  }

  DEV2_VAGRANT_WORDMARK(ivb) {
    DEV2_ORACLE_ORIGINAL(vbox, Virtual Box) {
      DEV2_UBUNTU_WORDMARK(vboxubuntu, Server) {
        TOOL_DOCKER(vboxdockerce, Docker CE) {
        }
      }
    }
  }
  dc ..down.> ocidockerce
  dc ..down.> wdd
  dc ..down.> vboxdockerce
}
c -------> i
}

@enduml